### ISSUE TITLE
Problems on Safari

### ISSUE THREAD

**Issue by davidbwaters** [dvLden/Vidage#11]
Hi, I'm using Vidage 0.3.0 on [this](http://1millionfit.com/) site.  I'm on Windows and am unable to try to debug the Safari version, but am getting reports it's not working in Safari.  It's working for me in Chrome.  I'm told the demo is working.  Any ideas?  Thanks.

**Comment by dvLden** [comment]
Hello there,
I was able to track down the issue but I am unsure what is it about exactly. Whether Safari does not support `.mp4` and instead you should also include `.webm` (just assumption).

But here's the current problem that shows up on your site...
<img width="1440" alt="screen shot 2017-01-15 at 8 03 40 pm" src="https://cloud.githubusercontent.com/assets/3460368/21965339/4e89c856-db5e-11e6-843f-8dfeae2400a8.png">

**Comment by davidbwaters** [comment]
Thanks, I'll try that.  Thanks for helping me isolate this.
