### ISSUE TITLE
It works in IE

### ISSUE THREAD

**Issue by lgg** [dvLden/Vidage#2]
IE 10 and IE Edge works fine for me. Why in Readme: 
> Unfortunately, I was unable to determine the issue on Internet Explorer. It just shows up the cover image, but never plays the video. :'(

win7 64x, ie edge

**Comment by dvLden** [comment]
I've been testing using BrowserStack in all IE's and it did not work in any 😞 , so I am not sure how it works for you 😮 ?

**Comment by dvLden** [comment]
**Update**

I just tested once again and seems like you're right, but I am not wrong either.
**It does work** in IE 10 & 11 on Windows 7.

But **it does not work** on IE 10 & 11 on Windows 8, 8.1 and 10. Which is weird...

**Comment by littleguga** [comment]
@dvLden hmm, it's really strange. Unfortunately i only have win7, so i can't help with 8, 8,1 and 10.

**Comment by dvLden** [comment]
I'll ask some of my friends to test. I have OS X only...
Thanks for testing it on Windows 7, that means there is a chance I may get it working for other Windows versions too.

**Comment by dvLden** [comment]
I did some testing today and turns out that on Windows 8, 8.1 and 10 the IE returns true for touch detection. I am aware that there are many laptops with touch support, but it's false positive if the touch is supported in browser and device is not having touch support. Anyways, I wrote this one liner and it seems to be working.

`window.navigator.userAgent.indexOf('MSIE') > 0 || !!window.navigator.userAgent.match(/Trident\/7\./);`

So, I think I will add this in Vidage and push another version. This would mean that it will be working in IE 9+, but I don't know for sure if 9 will be supported. If anyone has IE 9, let me know if the one liner above in console returns true or false. Thanks!

**Comment by littleguga** [comment]
@dvLden if we can trust to Developer mode in Edge:
it returns `true`

![image](https://cloud.githubusercontent.com/assets/12018713/17453474/ecf61ad0-5b84-11e6-83d6-03be9e0e977f.png)

**Comment by dvLden** [comment]
Can you download IE 9 or 10 on your machine? 
It's good that it returned true in Edge.

**Comment by dvLden** [comment]
I tested in IE 9 there's a problem with `window.matchMedia` but I guess it would work with polyfill, so I'll mention that in **README.md**. Edge 13/14 already works right now but if I add that check or this one (pretty much similar)

`window.navigator.userAgent.indexOf('MSIE') > 0 || !!window.navigator.userAgent.match(/Trident.*rv\:11\./)`

It should return false in Edge Browsers, but true in IE's. As far as I tested it's like that for me. 
Can you try once again both of checks and see if one returns false for you in Edge?

**1:**
`window.navigator.userAgent.indexOf('MSIE') > 0 || !!window.navigator.userAgent.match(/Trident\/7\./);`

**2:**
`window.navigator.userAgent.indexOf('MSIE') > 0 || !!window.navigator.userAgent.match(/Trident.*rv\:11\./)`

Thanks in advance man!

**Comment by andrey-hohlov** [comment]
WIndows 10 + IE11, not working:
`window.navigator.userAgent.indexOf('MSIE') > 0 || !!window.navigator.userAgent.match(/Trident\/7\./);`
true
`window.navigator.userAgent.indexOf('MSIE') > 0 || !!window.navigator.userAgent.match(/Trident.*rv\:11\./);`
true

WIndows 10 + Edge, works:
`window.navigator.userAgent.indexOf('MSIE') > 0 || !!window.navigator.userAgent.match(/Trident\/7\./);`
false
`window.navigator.userAgent.indexOf('MSIE') > 0 || !!window.navigator.userAgent.match(/Trident.*rv\:11\./);`
false

Also I have vm with Windows 7 and IE9/IE10 and can test in it.

**Comment by dvLden** [comment]
Well, it's good thing. 
It is suppoused to return `true` in IE's and false in Edge's.

I will implement this later on today to make it work in IE's. ( I think IE 10/11 will be working and not IE 9). Further tests would be needed.

**Comment by dvLden** [comment]
Fixed in `0.2.0`. Tested on BrowserStack and it works great in following:

Windows 8, 8.1 - IE 10/11
Windows 10 - IE 11, Edge 13/14
