### ISSUE TITLE
Why there is no info about needed css in readme?

### ISSUE THREAD

**Issue by littleguga** [dvLden/Vidage#3]
I thought that js script will auto insert/create css rules for background image, but it didn't.

Maybe i'm doing smth wrong?

**Comment by dvLden** [comment]
Yeh, I should've mentioned it probably. 👍 
No it won't automatically inject any CSS. Let's keep it clean and separated 🚨 

`<link href="styles/Vidage.css" rel="stylesheet">`

I will resolve NPM issue and update README based on your suggestion.
