### ISSUE TITLE
npm 0.1.3 Vidage.min.js missed

### ISSUE THREAD

**Issue by iamaleky** [dvLden/Vidage#4]
I have Vidage as dependency and tooled gulp task for copying .min.js file, unfortunately in last 0.1.3 release Vidage.min.js is missed

**Comment by dvLden** [comment]
If I understand properly, you've used your own gulp tasks to copy `Vidage.min.js` file, but the file no longer exists?

If so, that's correct. I've decided that there's no need for non-minified JS version as it's unreadable after source version goes through compile. So now you should probably just copy Vidage.js as that's the only version and it's minfied.

I also throw out .min suffix as it's unnecessery when there are only minified files (CSS and JS) included in destionation.

**Comment by iamaleky** [comment]
@dvLden thanks for info.

We have such project structure:
-project
--dist
---assets
---index.html
--node_modules
--sources
--gulpfile.js

On production server it's served from /dist/ folder. So we need to copy deps from node_modules to /dist/assets

**Comment by dvLden** [comment]
So I assume you store each filename that you need found and copied within node_modules? 
It's strange to me tho, why you're not running an compiler and including the dependencies from node_modules as suppoused. In the end they get compiled in single file that you should throw in dist, right? At least that makes sense to me.

**Comment by iamaleky** [comment]
@dvLden in cause of dynamic loading for libraries. Single complied file will be too large ;)
