### ISSUE TITLE
QQ – Android Messanger App (China)

### ISSUE THREAD

**Issue by uniquexiaobai** [dvLden/Vidage#9]
Only in Android mobile QQ, when open a web page with Vidage, it automatically plays the background video instead of the background image.

![screenshot_2016-10-25-08-17-40-209_com tencent mo](https://cloud.githubusercontent.com/assets/12796673/19668774/94271214-9a8c-11e6-9597-418f5bf2842c.png)

**Comment by dvLden** [comment]
More information please...

- Android version
- Which phone and model
- Orientation (assuming it's landscape by SS)

<img width="409" alt="screen shot 2016-10-25 at 2 32 13 am" src="https://cloud.githubusercontent.com/assets/3460368/19668916/7212f566-9a5b-11e6-8d40-175ed2fe6569.png">
<img width="710" alt="screen shot 2016-10-25 at 2 33 59 am" src="https://cloud.githubusercontent.com/assets/3460368/19668927/81cfb4bc-9a5b-11e6-926e-91d2bbf3051a.png">

**Comment by uniquexiaobai** [comment]
android 6, most of the mobile phone brand in China, like MIUI, Smartisan... No problem in the android browser, only in **android mobile phone QQ software**.
![Uploading Screenshot1.png…]()
![Uploading Screenshot2.png…]()

**Comment by uniquexiaobai** [comment]
android 6, most of the mobile phone brand in China, like MIUI, Smartisan... No problem in the android browser, only in **android mobile phone QQ software**.

![screenshot2](https://cloud.githubusercontent.com/assets/12796673/19803306/7fa57a82-9d3a-11e6-973f-589137e78c3f.png)
![screenshot1](https://cloud.githubusercontent.com/assets/12796673/19803312/847292f2-9d3a-11e6-9edc-9ec9f974cc49.png)

**Comment by dvLden** [comment]
Oh I see, we have a misunderstanding in conversation.

What is "QQ Software" I have no ideas?

I found this:
[QQ Android](https://play.google.com/store/apps/details?id=com.tencent.mobileqq&hl=en)
But I have no ideas what is that and what is it for...

Can you link me to **this** or **those** _QQ apps_ and tell me what they are for?

**Comment by uniquexiaobai** [comment]
QQ is a instant messaging software like Messenger、Skype，you can download it [here](http://dldir1.qq.com/qqfile/QQIntl/QQi_wireless/Android/qqi_4.6.13.6034_office.apk).

**Comment by dvLden** [comment]
Unfortuately, I am unable to download any apps on **BrowserStack**, so I'm unable to do any testing...

That QQ messanger is using their own browser when any links were tapped through the messanger? Assuming...

If you can do any tests of Vidage's – feature detect options, I'd appreciate a feedback.

```
const feature = {
    touch: !!(('ontouchstart' in window)
            || window.navigator && window.navigator.msPointerEnabled && window.MSGesture
            || window.DocumentTouch && document instanceof DocumentTouch),
    ie: window.navigator.userAgent.indexOf('MSIE') > 0
        || !!window.navigator.userAgent.match(/Trident.*rv\:11\./),
    small: window.matchMedia('(max-width: 34em)').matches
};

// I'd need each option
feature.touch
feature.ie
feature.small

// And this
(feature.touch && !feature.ie) || feature.small
```

**Comment by dvLden** [comment]
If anyone is willing to tracking down the issue for this, feel free to help out!
For now... Closing.
